[versions]
ideProbe = "0.52.0"
detekt = "1.23.1"
kotlin-gradle-version = "1.9.0"

[libraries]
ideProbeDriver = { module = "org.virtuslab.ideprobe:driver_2.13", version.ref = "ideProbe" }
ideProbeRobot = { module = "org.virtuslab.ideprobe:robot-driver_2.13", version.ref = "ideProbe" }
junitJupiter = { module = "org.junit.jupiter:junit-jupiter", version = "5.9.3" }
bsp4j = { module = "ch.epfl.scala:bsp4j_2.13", version = "2.1.0-M6.alpha" }
kotest = { module = "io.kotest:kotest-assertions-core", version = "5.6.2" }
scala = { module = "org.scala-lang:scala-library", version = "2.13.11" }
gson = { module = "com.google.code.gson:gson", version = "2.10.1" }
detektFormatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detektGradle = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
kotlinGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-gradle-version" }
coursier = { module = "io.get-coursier:coursier_2.13", version = "2.1.5" }

[plugins]
intellij = { id = "org.jetbrains.intellij", version = "1.15.0" }
changelog = { id = "org.jetbrains.changelog", version = "2.1.2" }
